package application;
import java.sql.SQLException;
import DsAppl.Candidat;
import DsAppl.DaoCandidat;
import javafx.fxml.FXML;
import javafx.scene.chart.PieChart.Data;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;
import javafx.scene.control.TableView;
import javafx.scene.control.TableColumn;
public class MnController {
	@FXML
	private TextField lastname;
	@FXML
	private Button btCreate;
	@FXML
	private Button btnread;
	@FXML
	private Button btnUpdate;
	@FXML
	private TextField firstname;
	@FXML
	private TextField id;
	@FXML
	private TextField email;
	@FXML
	private TableView tableView;
	@FXML
	private TableColumn clmnIdCandidat;
	@FXML
	private TableColumn clmnNomCandidat;
	@FXML
	private TableColumn clmnPrenomCandidat;
	@FXML
	private TableColumn clmnEmailCandidat;
	@FXML
	private TableColumn clmnAdresseCandidat;
	@FXML
	private TableColumn clmnVilleCandidat;
	@FXML
	private TableColumn clmnPaysCandidat;
	@FXML
	private TextField city;
	@FXML
	private TextField country;
	@FXML
	private TextField adresse;
	@FXML
	private TextField idCandidat;
	@FXML
	private Button btndelete;
	
	// Event Listener on Button[#btCreate].onAction
	@FXML
	public void Create (ActionEvent event) {
	   int Id = Integer.parseInt(id.getText());
		 Candidat candidat = new Candidat(8, "nawal","Boulahsire", "nawalbila80@gmail.com","Rue657N79" , "agadir", "Maroc");
	     candidat.setId(Id);
		candidat.setFirstName(firstname.getText());
		candidat.setLastName(lastname.getText());
		candidat.setEmail(email.getText());
		candidat.setAdresse(adresse.getText());
		candidat.setCity(city.getText());
		candidat.setCountry(country.getText());

		 System.out.println("Candidate Create successfully" );
	}
	  /*  data.addAll(DaoCandidat.getAll()) ;
		tableView.refresh();
	  	DaoCandidat.getAll();
       if(candidatDao.create(candidat) !=null) {
			tableView.refresh();
			}*/
	
	// Event Listener on Button[#btnread].onAction
	@FXML
	public void read(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnUpdate].onAction
	@FXML
	public void update(ActionEvent event) {
			
			 int Id  = Integer.parseInt(idCandidat.getText());
			 Candidat candidat = new Candidat(Id, "lilan", "bikan", "lilanbik@gmail.com","etage2N445", "fes", "maroc");
			 candidat.setId(Id);
		candidat.setFirstName(firstname.getText());
		candidat.setLastName(lastname.getText());
		candidat.setEmail(email.getText());
		candidat.setAdresse(adresse.getText());
		candidat.setCity(city.getText());
		candidat.setCountry(country.getText());
		System.out.println("Candidate  updated successfully" );
		};
		
	// Event Listener on Button[#btndelete].onAction
	@FXML
	public void delete(ActionEvent event) {

			Candidat  candidat = (Candidat) tableView.getSelectionModel().getSelectedItem();
			if(candidat.delete(candidat.getId())){
			if(candidat!=null);
		    }		
		int selectedIndex = tableView.getSelectionModel().getSelectedIndex();
	    if (selectedIndex >= 0) {
	        tableView.getItems().remove(selectedIndex);

	    } else {
	       
	        Alert alert = new Alert(AlertType.WARNING);
	        alert.setTitle("No Candidate Has been selected");
	        alert.setHeaderText("No candidate Selected");
	        alert.setContentText("Please select a Candidat in the table.");
	        alert.showAndWait();            

	    }
	}
	 void clear() {
		 idCandidat.setText(null);
		 firstname.setText(null);
		 lastname.setText(null);
		 email.setText(null);
		 adresse.setText(null);
		 city.setText(null);
		 country.setText(null);
	
		}
	}